const names = [
  'Aaran',
  'Aaren',
  'Aarez',
  'Aarman',
  'Aaron',
  'Aaron-James',
  'Aarron',
  'Aaryan',
  'Aaryn',
  'Aayan',
  'Aazaan',
  'Abaan',
  'Abbas',
  'Abdallah',
  'Abdalroof',
  'Abdihakim',
  'Abdirahman',
  'Abdisalam',
  'Abdul',
  'Abdul-Aziz',
  'Abdulbasir',
  'Abdulkadir',
  'Abdulkarem',
  'Smith',
  'Jones',
  'Coollastname',
  'enter_name_here',
  'Ze',
  'Zechariah',
  'Zeek',
  'Zeeshan',
  'Zeid',
  'Zein',
  'Zen',
  'Zendel',
  'Zenith',
  'Zennon',
  'Zeph',
  'Zerah',
  'Zhen',
  'Zhi',
  'Zhong',
  'Zhuo',
  'Zi',
  'Zidane',
  'Zijie',
  'Zinedine',
  'Zion',
  'Zishan',
  'Ziya',
  'Ziyaan',
  'Zohaib',
  'Zohair',
  'Zoubaeir',
  'Zubair',
  'Zubayr',
  'Zuriel',
  'Xander',
  'Jared',
  'Courtney',
  'Gillian',
  'Clark',
  'Jared',
  'Grace',
  'Kelsey',
  'Tamar',
  'Alex',
  'Mark',
  'Tamar',
  'Farish',
  'Sarah',
  'Nathaniel',
  'Parker',
];

const thoughts = [
  "fugiat adipisicing non Lorem voluptate",
  "nisi adipisicing id consequat labore",
  "eiusmod eiusmod laborum reprehenderit sunt",
  "aute reprehenderit laboris labore Lorem",
  "ex voluptate non ad qui",
  "do nulla elit commodo culpa",
  "aliqua reprehenderit incididunt aliquip irure",
  "laborum esse dolor id velit",
  "quis aute do est officia",
  "culpa ipsum sint dolore et",
  "deserunt ex duis veniam voluptate",
  "incididunt aliqua non consequat elit",
  "officia sint magna non nisi",
  "ut ea consequat cupidatat sint",
  "mollit nulla reprehenderit laboris reprehenderit",
  "voluptate excepteur ullamco cupidatat duis",
  "reprehenderit ea dolor incididunt incididunt",
  "qui fugiat non occaecat et",
  "aute velit elit mollit cillum",
  "qui incididunt excepteur anim anim",
  "tempor aliquip excepteur esse elit",
  "occaecat minim veniam dolor excepteur",
  "commodo labore fugiat minim sit",
  "nulla pariatur eiusmod et est",
  "do fugiat veniam irure est",
  "eu elit elit ipsum irure",
  "quis id dolor enim occaecat",
  "aliqua laborum nisi commodo culpa",
  "reprehenderit reprehenderit laboris ea ullamco",
  "nulla proident reprehenderit aute voluptate",
  "fugiat adipisicing Lorem pariatur commodo",
  "sit fugiat consectetur nisi nulla",
  "tempor ut id in do",
  "et eiusmod enim sunt magna",
  "veniam ad tempor eiusmod ullamco",
  "anim dolore proident minim sit",
  "officia est excepteur consectetur officia",
  "cupidatat consequat elit aliquip est",
  "non exercitation elit aute non",
  "reprehenderit do eu exercitation consectetur",
  "consectetur veniam reprehenderit eu ea",
  "duis do tempor in elit",
  "irure nulla excepteur officia in",
  "ipsum labore irure mollit ut",
  "consequat eu aliqua est ex",
  "laborum officia ut nostrud et",
  "laboris sit sit consequat magna",
  "et ullamco commodo pariatur occaecat",
  "reprehenderit ad reprehenderit aliquip irure",
  "culpa ipsum ut ex ut",
  "deserunt nostrud anim enim ex",
  "eu quis consequat reprehenderit ut",
  "consequat est aute excepteur eu",
  "in veniam adipisicing consequat consectetur",
  "magna non enim deserunt ullamco",
  "incididunt mollit veniam cupidatat tempor",
  "dolore enim consequat ea cillum",
  "ipsum amet ut nisi nostrud",
  "deserunt ex anim cupidatat adipisicing",
  "quis id do anim nisi",
  "proident qui quis occaecat ad",
  "Lorem duis fugiat ea sint",
  "ullamco ullamco eiusmod Lorem ut",
  "qui ea consequat labore duis",
  "aliqua dolor incididunt cillum voluptate",
  "voluptate tempor labore officia est",
  "fugiat ullamco cillum duis duis",
  "pariatur occaecat exercitation adipisicing deserunt",
  "ad exercitation ullamco consectetur consequat",
  "do elit voluptate dolore tempor",
  "ut ipsum aliquip id minim",
  "reprehenderit magna officia sit sit",
  "Lorem deserunt reprehenderit ex incididunt",
  "voluptate consequat est et voluptate",
  "ullamco Lorem consectetur anim reprehenderit",
  "velit eu et non consectetur",
  "incididunt sit enim cillum in",
  "commodo irure voluptate consequat ex",
  "dolor magna ea ex reprehenderit",
  "esse incididunt ipsum Lorem officia",
  "nisi et veniam duis nulla",
  "labore ut minim excepteur consequat",
  "veniam do Lorem ad ex",
  "Lorem aute quis quis minim",
  "minim cillum eu anim veniam",
  "fugiat anim adipisicing irure labore",
  "reprehenderit nostrud dolore minim nulla",
  "in ullamco officia adipisicing nostrud",
  "eiusmod voluptate non ex cupidatat",
  "ad adipisicing amet fugiat adipisicing",
  "cupidatat proident in quis cillum",
  "culpa proident id voluptate mollit",
  "nulla magna sit exercitation culpa",
  "sint duis ut laborum anim",
  "elit nostrud magna mollit nostrud",
  "exercitation anim et nostrud cupidatat",
  "duis ea ipsum laborum tempor",
  "pariatur do ipsum officia ad",
  "fugiat Lorem labore esse laborum",
  "voluptate eu non enim proident"
];

const reactions = [
  'happy',
  'angry',
  'surprised',
  'confused',
  'like',
  'dislike',
  'love',
  'hate'
];

// Get a random item given an array
const getRandomArrItem = (arr) => arr[Math.floor(Math.random() * arr.length)];

const getRandomUsernames = (int) => {
  const users = [];
  for (let i = 0; i < int; i++) {
    users.push(`${getRandomArrItem(names)}${getRandomArrItem(names)}`);
  }
  return users;
}

const getRandomReactions = (int, usernames) => {
  const reactionsArr = []
  for (let i = 0; i < int; i++) {
    reactionsArr.push({
      reactionBody: getRandomArrItem(reactions),
      username: getRandomArrItem(usernames)
    });
  }
  return reactionsArr;
};
const getRandomThought = () => getRandomArrItem(thoughts);

// Export the functions for use in seed.js
module.exports = { getRandomUsernames, getRandomThought, getRandomReactions };
